apiVersion: apps/v1
kind: Deployment
metadata:
  name: openebs-upgrade
  namespace: openebs-test
spec:
  replicas: 1
  selector:
    matchLabels:
      name: openebs-upgrade
  template:
    metadata:
      labels:
        name: openebs-upgrade
    spec:
      containers:
      - name: openebs-upgrade
        image: sagarkrsd/openebs-upgrade:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        command: ["/usr/bin/openebs-upgrade"]
        args:
        - --logtostderr
        - --run-as-local
        - -v=5
        - --discovery-interval=40s
        - --cache-flush-interval=240s
        resources:
      serviceAccountName: openebsupgrade
