apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: openebs-operator
  name: openebs-operator
  namespace: openebs
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prometheus-operator
    spec:
      containers:
      - name: openebs-operator
        image: sagarkrsd/openebs-operator:latest
        ports:
        - containerPort: 8080
        resources:
      serviceAccountName: openebs-operator
