apiVersion: v1
kind: ServiceAccount
metadata:
  name: openebsoperator
  namespace: openebs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openebsoperator
rules:
- apiGroups:
  - "apiextensions.k8s.io"
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - "dao.mayadata.io"
  resources:
  - openebses
  verbs:
  - '*'
- apiGroups:
  - "*"
  resources:
  - deployments
  - replicasets
  - jobs
  - cronjobs
  - statefulsets
  - daemonsets
  - configmaps
  - secrets
  - services
  - namespaces
  verbs:
  - '*'
- apiGroups:
  - "*"
  resources:
  - pods
  verbs:
  - list
  - delete
- apiGroups:
  - "*"
  resources:
  - nodes
  verbs:
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openebsoperator
subjects:
- kind: ServiceAccount
  name: openebsoperator
  namespace: openebs
roleRef:
  kind: ClusterRole
  name: openebsoperator
  apiGroup: rbac.authorization.k8s.io
---
