apiVersion: metac.openebs.io/v1alpha1
kind: GenericController
metadata:
  name: sync-openebs
  namespace: openebs-operator
spec:
  updateAny: true
  watch:
    apiVersion: dao.mayadata.io/v1alpha1
    resource: openebses
  attachments:
  - apiVersion: dao.mayadata.io/v1alpha1
    resource: openebses
  - apiVersion: apps/v1
    resource: daemonsets
    updateStrategy:
      method: InPlace
    advancedSelector:
      selectorTerms:
      - matchReferenceExpressions:
        - key: metadata.annotations.dao\.mayadata\.io/openebs-uid
          refKey: metadata.uid # match this ann value against watch UID
  - apiVersion: apps/v1
    resource: deployments
    updateStrategy:
      method: InPlace
    advancedSelector:
      selectorTerms:
      - matchReferenceExpressions:
        - key: metadata.annotations.dao\.mayadata\.io/openebs-uid
          refKey: metadata.uid # match this ann value against watch UID
  - apiVersion: v1
    resource: configmaps
    updateStrategy:
      method: InPlace
    advancedSelector:
      selectorTerms:
      - matchReferenceExpressions:
        - key: metadata.annotations.dao\.mayadata\.io/openebs-uid
          refKey: metadata.uid # match this ann value against watch UID
  - apiVersion: v1
    resource: services
    updateStrategy:
      method: InPlace
    advancedSelector:
      selectorTerms:
      - matchReferenceExpressions:
        - key: metadata.annotations.dao\.mayadata\.io/openebs-uid
          refKey: metadata.uid # match this ann value against watch UID
  - apiVersion: rbac.authorization.k8s.io/v1beta1
    resource: clusterrolebindings
    updateStrategy:
      method: InPlace
    advancedSelector:
      selectorTerms:
      - matchFields:
          metadata.name: "openebs-maya-operator"
  - apiVersion: rbac.authorization.k8s.io/v1beta1
    resource: clusterroles
    updateStrategy:
      method: InPlace
    advancedSelector:
      selectorTerms:
      - matchFields:
          metadata.name: "openebs-maya-operator"
  - apiVersion: v1
    resource: serviceaccounts
    updateStrategy:
      method: InPlace
    advancedSelector:
      selectorTerms:
      - matchReferenceExpressions:
        - key: metadata.annotations.dao\.mayadata\.io/openebs-uid
          refKey: metadata.uid # match this ann value against watch UID
  hooks:
    sync:
      inline:
        funcName: sync/openebs
